### ISSUE TITLE
Broken on Laravel 5 (gasp!)

### ISSUE THREAD

**Issue by RyanThompson** [jenssegers/laravel-agent#25]
Although it's a bit taboo right now - this is of course broken on L5.

Easy to fix though. Remove the boot method from your provider. It's not needed. The package does not require any config or anything. 

I have a fork and did just that and have been using it happily for probably a month. 

Cheers!

**Comment by jenssegers** [comment]
Dropped it in the last commit. I don't think it is even needed in L4.

**Comment by RyanThompson** [comment]
Killer! Thanks for the quick reply man.

**Comment by RyanThompson** [comment]
Minor version bump? ^_^

**Comment by jenssegers** [comment]
Done

**Comment by RyanThompson** [comment]
You rock
