### ISSUE TITLE
IE9 on Windows 7 logs as IE7

### ISSUE THREAD

**Issue by vicrau** [jenssegers/laravel-agent#26]

**Comment by jenssegers** [comment]
Example user agent?

**Comment by vicrau** [comment]
I have the following code:

    $browser = Agent::browser();
    $browserVersion = Agent::version($browser);
    $platform = Agent::platform();
    $platformVersion = Agent::version($platform);
    $agent = $platform . " " . $platformVersion . " -- " . $browser . " " . $browserVersion;

And it outputs:
    Windows 6.1 -- IE 7.0

I asked for a screenshot with more info about the browser:

![image001](https://cloud.githubusercontent.com/assets/541611/5954781/6217a3ea-a79c-11e4-9f1a-adb1fe464412.jpg)

**Comment by vicrau** [comment]
this is the user-agent from the same user as the screenshot:

Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/5.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; MS-RTC LM 8; Zune 4.7; Media Center PC 6.0; .NET4.0C; .NET4.0E; InfoPath.3)

**Comment by jenssegers** [comment]
Isn't `MSIE 7.0` Internet Explorer 7? That's one weird user agent string.

**Comment by vicrau** [comment]
http://www.useragentstring.com/ tells me this:

Internet Explorer version 7.0 (MSIE 9.0 in 7.0 Compatibility View)

**Comment by jenssegers** [comment]
Apparently `Trident/5.0` means that it's coming from an IE9 browser. It's a bit of an edge case actually. To fix this I would have to add custom code for IE only, which I would rather not do of course :)

In case of IE, you could try to check for:

    Agent::version('Trident');

This will return `5` in this case. To get the actual IE number, you need to add `4` to it.

**Comment by vicrau** [comment]
ok, thanks!

I'll try to convince the the customer to disable that mode first :-)
