### ISSUE TITLE
Class 'App\Agent' not found

### ISSUE THREAD

**Issue by mihai-craita** [jenssegers/laravel-agent#33]
I installed using composer as in the description.

I tried composer dumpautoload, I reinstalled the package and still the same error.

I'm doing something wrong?

Mention: I use laravel 5.

**Comment by jenssegers** [comment]
You are not using the correct namespace. If you have added it to the alias list, then you should use `\Agent` or `use Agent;`

**Comment by mihai-craita** [comment]
Thanks, man! It works now! :)
