### ISSUE TITLE
Chrome OS Detection

### ISSUE THREAD

**Issue by Angelo8828** [jenssegers/laravel-agent#34]
Hello and good day,

I will be straightforward and I just want to report that your tool Sir cannot detect Chrome OS so far. Instead it returns 0. 

Here is a sample user-agent for Chrome OS: 'Mozilla/5.0 (X11; CrOS x86_64 6680.78.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.102 Safari/537.36'.

Thanks a lot and may the Force be with you.

**Comment by jenssegers** [comment]
Fixed on dev-master :)

**Comment by Angelo8828** [comment]
Thanks a lot.
